version: '2'

services:
  haproxy:
    image: haproxy:1.8
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      default:
        ipv4_address: 172.16.241.10

  syslog:
    image: balabit/syslog-ng
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
    networks:
      default:
        ipv4_address: 172.16.241.12

  web1:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-www.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        ipv4_address: 172.16.241.21

  web2:
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx-www.conf:/etc/nginx/conf.d/default.conf
    networks:
      default:
        ipv4_address: 172.16.241.22

  php1:
    image: php:7-fpm
    volumes:
      - ./html:/var/www/html
      - ./php-ping.conf:/usr/local/etc/php-fpm.d/ping.conf
    networks:
      default:
        ipv4_address: 172.16.241.31

  php2:
    image: php:7-fpm
    volumes:
      - ./html:/var/www/html
      - ./php-ping.conf:/usr/local/etc/php-fpm.d/ping.conf
    networks:
      default:
        ipv4_address: 172.16.241.32

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.241.0/24
